### ISSUE TITLE
"Configuration.DkimSigner.exe is not a valid Win32 application" error in Windows Server 2003

### ISSUE THREAD

**Issue by obramin** [Pro/dkim-exchange#101]
Archive is ok, file not locked, but i can't execute it. =(
![ejlj4xvah0s9urnrhdigxa](https://cloud.githubusercontent.com/assets/15092843/10433652/7b1d9c4c-7135-11e5-8da1-5667d2f0fbb3.jpg)

**Comment by Pro** [comment]
Honestly I never tried it on a Windows Server 2003 and since it's a quite old OS (support ended in July 2015) it's not supported by this signer.
The problem here is that the app is compiled for 64 bit and you installed a 32 bit windows which won't work.
You can try the manual installation, maybe that works? (see https://github.com/Pro/dkim-exchange#manual-install and https://github.com/Pro/dkim-exchange#manual-configuration)

**Comment by obramin** [comment]
OS version is 64-bit =( 
![gm3cte8i5uw6mlxc3nsg](https://cloud.githubusercontent.com/assets/15092843/10717226/4202641a-7b7b-11e5-9bd3-31ec857d24a7.jpg)

**Comment by AlexLaroche** [comment]
Windows Server 2003 doesn't support .NET 4.5.
Windows Server 2003 only support .NET 4.0.

The configuration tool need .NET 4.5.
The signer need .NET 2.0 or .NET 4.0. (see documentation for more details)

You could manually install the DKIM Signer agent.
