### ISSUE TITLE
Sender and Recepient rule deprecated?

### ISSUE THREAD

**Issue by stevemayster** [Pro/dkim-exchange#105]
Hello.
I don't think it's a issue but i don't know where to ask.
Is Sender and Recepient rule deprecated in v2.1.7?
I want to try dkim-exchange but don't want to local message signed,only remote.
In new example config sender and recepient rule not present.
Can i use this config?
Domain Domain="example.org" Selector="sel2013" PrivateKeyFile="keys/example.org.private" RecipientRule="yahoo\.[^\.]+"

**Comment by Pro** [comment]
We removed those rules in version 2.0 since it caused some inconsistencies and problems.

I'm not 100% sure, but as far as I remember local/internal messages aren't signed if they aren't sent to another server. 
Currently there aren't any plans to readd this feature. If someone is willing to spend some time on this, we can assess reintegrating it.

**Comment by stevemayster** [comment]
Hello, Pro!
Many thanks for answer!
