### ISSUE TITLE
Existing DNS: No record found

### ISSUE THREAD

**Issue by meluvalli** [Pro/dkim-exchange#152]
I have been using Exchange DKIM signer for a while now and have had the problem for a long time...  Doesn't matter what version I am running.

Existing DNS under Domain Settings ALWAYS shows No record found...

Simple nslookup on the server using the below commands:
set q=txt
s1024._domainkey.mydomain.com

Returns the domain key text without any problems.

Not sure why the program can't see it.

**Comment by Pro** [comment]
Can you tell me your domain (or send it to me via private email: http://profanter.me/contact) so I can debug it?

Please also include the selector which you currently use.

**Comment by meluvalli** [comment]
Sent VIA PM

**Comment by Pro** [comment]
I'll move the discussion here:
I tested with your domain and it worked for me.

@meluvalli responded:
It's something to do with my server using ROOT hints instead of a forwarder.   I wonder what would cause that???

We are using the DNS Servers specified by windows:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/MainWindow.cs#L1002
Which calls:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/Dns/Resolver.cs#L124
and uses the default DNS servers specified for all the network interfaces:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/Dns/Resolver.cs#L547

Then it's up to the Windows Server to get the responsible Nameserver for the given domain.

**Comment by VickyKhan123** [comment]
I am facing the same issue, I checked the DKIM record from MX toolbox etc and it is fine, only DKIM Signer is unable to find the record.
After that i made an entry of the same DKIM under the local DNS and it  found the entry but now after sending the test email id the result failed with the below error message:

Validating Signature

result = fail
Details: OpenSSL error: data too small for key size

key length is 1024
