### ISSUE TITLE
CrossTenant messages not signed

### ISSUE THREAD

**Issue by VladlenBulatov** [Pro/dkim-exchange#159]
### Versions

- **Windows Server Version**: 2012 R2
- **Exchange Version**: 15.0.1178.4
- **Installed DKIM Exchange Version**: 3.0.4

### Description

CrossTenant messages not signed while routed by high prority filters

[Description of the bug or feature]

dkim-agent installed on MB-servers.
External messages are signed correctly (routed to gmail or so on)
But cross-tenant (from onpremise to office 365) not signed as routed by hi priority filters

**Expected behavior:** sign before route events

**Actual behavior:** not signed, but routed to external (CrossTenant) servers

**Comment by VladlenBulatov** [comment]
Sorry it a not of routing problem is a TNEF related problem

**Comment by Pro** [comment]
If the message contains a TNEF part, it won't be signed, that's on purpose because they are normally internal messages.
See the comment here: https://github.com/Pro/dkim-exchange/blob/64dc22248c3a9f87e7d5d0ad6bc1252da8080776/Src/Exchange.DkimSigner/DkimSigningRoutingAgent.cs#L91

Hope this answers your question.
