### ISSUE TITLE
Check your internet connection in computer with internet.

### ISSUE THREAD

**Issue by j0rt3g4** [Pro/dkim-exchange#198]
### Versions (Latest)

Couldn't get current version.
Check your Internet connection or restart the application.

### Description
I uninstalled the previous version 3.0.8
and I wanted to update to 3.0.12
now... I got that error:
Couldn't get current version.
Check your Internet connection or restart the application.

The computer has internet and it's enabled
http://prntscr.com/gzwf2e

**Comment by Westernstandard** [comment]
I am getting this too (on 3.0.13) and since it can't check for newer versions, it never offers the option to do the installation via the GUI. Tried doing the manual install, but the install.ps1 script is not part of the latest release. It must be downloaded as part of the full source. After running the script (has errors), Transport service will not restart. Must uninstall to get it running again.

**Comment by coolwebcool** [comment]
got the same issue recently, any update?

**Comment by Westernstandard** [comment]
I've committed a fix that would resolve the issue if it is accepted into the main branch. In Microsoft's infinite wisdom, they determined that the security selector would operate in both a restrictive and permissive form. By default, they allow SSL3 and TLS1.0, but they also restrict to those two protocols. Since Github is now probably running TLS1.2, it is not permitted. I've uploaded a fix to permit (and restrict) SSL3, TLS1.0, TLS1.1, and TLS1.2. If you're savy with the code, I can tell you where to add it to the source code so you can compile it yourself.

**Comment by Westernstandard** [comment]
I've committed a fix that would resolve the issue if it is accepted into the main branch. In Microsoft's infinite wisdom, they determined that the security selector would operate in both a restrictive and permissive form. By default, they allow SSL3 and TLS1.0, but they also restrict to those two protocols. Since Github is now probably running TLS1.2, it is not permitted. I've uploaded a fix to permit (and restrict) SSL3, TLS1.0, TLS1.1, and TLS1.2. If you're savy with the code, I can tell you where to add it to the source code so you can compile it yourself.
Regards,

Richard Tregaskis
Western Standard Support
Em: support@westernstandard.com<mailto:support@westernstandard.com>
Ph: 801-224-7404

**Comment by coolwebcool** [comment]
@Westernstandard  thank you very much on the detail, but I totally new on the programing, So I have can not install the client on my new MX server as the version getting failed and the install buttom is gray, and try to install manually, but lot of error and mx services unable to start, so that I have to uninstall. wish have new version can fix this issue soon. Thank you!

**Comment by Westernstandard** [comment]
You can download the recompiled version here: [https://www.westernstandard.com/downloads/recompiled.7z](url) It will allow you to install, but you won't be able to get updates because the portion of the code is from the downloaded package during install.

**Comment by coolwebcool** [comment]
installed and working, Thanks a lot.

**Comment by davidenco** [comment]
Link is dead.

**Comment by Westernstandard** [comment]
Copy and paste the link in your browser. Github is doing something weird to the link and is redirecting it to Github. It's hosted on my webserver, not Github.

**Comment by davidenco** [comment]
Ah yes I see what it's doing now. Thanks.

**Comment by kgrossAK** [comment]
Westernstandard, I have downloaded your recompiled files, but I am unclear on where to put them.  Regardless of where I place those files, by searching the installation source, I am still encountering issues.

**Comment by Westernstandard** [comment]
It would help if you told us what issues you are encountering…

Regards,

Richard Tregaskis
Western Standard Support
Em: support@westernstandard.com<mailto:support@westernstandard.com>
Ph: 801-224-7404

**Comment by kgrossAK** [comment]
The symptoms where the transport service will not start while the agent is enabled/installed continue after using the recompiled files.  You mentioned in previous posts that the recompiled files must be installed, but I am not sure how to accomplish that.

**Comment by Westernstandard** [comment]
The solution is installed in a rather strange manner. You first download our recompiled application and run it (from any location, it could even be run on the desktop). At this point, the application will look for the latest signed version of the application on GitHub. This is where the original code fails because it can’t talk to GitHub with their new security. Our change allows this function to work. Once the application can find the latest signed version from GitHub, it downloads it and places it in the Program Files directory. Then it registers the service with Exchange. That copy in Program Files is then the one that is actually used.

The only changes we have made are in the part where the application looks for the latest signed version. Once it finds that, the version that is downloaded does not include our changes (meaning no further updates are possible until they include our code changes OR you uninstall and reinstall).

So if you have downloaded our code, run Configuration.DkimSigner.exe, and clicked on Install (on the Information tab), and completed the installation, then you are beyond the scope of what we can help you with.

Regards,

Richard Tregaskis
Western Standard Support
Em: support@westernstandard.com<mailto:support@westernstandard.com>
Ph: 801-224-7404

**Comment by kgrossAK** [comment]
Perfect!!!  Thanks so much!

**Comment by unik-web** [comment]
For those that don't know how to install recompiled version. 

1. Stop dkimsigner service. Then close the software.
2. Copy new files and put in folder **C:\Program Files\Exchange DkimSigner** (just in case backup folder)
3. Press button replace files.

Then it will work. Hope this will work for you.
