### ISSUE TITLE
Existing DNS Check

### ISSUE THREAD

**Issue by PetieM** [Pro/dkim-exchange#201]
### Versions

- **Windows Server Version**: 2008 R2 Datacenter
- **Exchange Version**: 14.3.123.4
- **Installed DKIM Exchange Version**: 3.0.12

### Description

I seem to be having trouble with the record checking feature on the Domain Settings tab. It's never worked for me and I figured maybe it was something that I did wrong but it now seems that it might have something to do with Google Domains DNS. I have one domain with the DNS at Namecheap and it works as expected but the rest of my domains, all of which are at Google Domains, do not. I'm not sure if this is something that you would need to fix or simply an issue with how Google handles its records but it's worth bringing up regardless. Thanks!

### Steps to Reproduce

1. Select a domain in the domain list.
2. Click Check under Existing DNS.

**Expected behavior:** DNS record loads and is validated as either correct or mismatched.

**Actual behavior:** Error message received: No record found for [selector]._domainkey.[domain]

**Comment by Pro** [comment]
Can you post one of your domains, where you set DKIM, so we can debug it?



On Sat, Dec 30, 2017 at 7:42 PM -0500, "Petie" <notifications@github.com<mailto:notifications@github.com>> wrote:

Versions

  *   Windows Server Version: 2008 R2 Datacenter
  *   Exchange Version: 14.3.123.4
  *   Installed DKIM Exchange Version: 3.0.12

Description

I seem to be having trouble with the record checking feature on the Domain Settings tab. It's never worked for me and I figured maybe it was something that I did wrong but it now seems that it might have something to do with Google Domains DNS. I have one domain with the DNS at Namecheap and it works as expected but the rest of my domains, all of which are at Google Domains, do not. I'm not sure if this is something that you would need to fix or simply an issue with how Google handles its records but it's worth bringing up regardless. Thanks!

Steps to Reproduce

  1.  Select a domain in the domain list.
  2.  Click Check under Existing DNS.

Expected behavior: DNS record loads and is validated as either correct or mismatched.

Actual behavior: Error message received: No record found for [selector]._domainkey.[domain]

-

**Comment by PetieM** [comment]
Of course! Sorry, I really should have done that to begin with. You can check against brokenrevolution.com. My selector is br if that helps as well.

**Comment by michelle911** [comment]
I am having the same issue - domain is barngroverglass.com select bgrmail

**Comment by Pro** [comment]
I could not check your issue since it looks like you already changed the domain settings. Is this bug still valid?

**Comment by PetieM** [comment]
I haven't changed anything about that domain and the problem is still present but I have an idea what might be going on. When trying to retrieve the key manually via nslookup, I get a message about the result being truncated and it retrying in TCP mode. I'm assuming the request happens by default over UDP and it can't return enough data without switching to TCP. My guess is that your query is explicitly using UDP and that the one that worked in the past from Namecheap worked not because of the registrar but because it had a shorter key (the rest of my domains are using 4096-bit keys).

**Comment by harrijon** [comment]
Same here. Existing DNS check always returns no record found.  ..which is not the case.

Exchange 2016 CU10
Win 2019
dkim signer: 3.1.0

**Comment by pipostyle** [comment]
i have same problem on windows server 2016 - exchange 2016 cu14
dkim signer 3.2.1
no record found but dkimvalidator web site return succes result

**Comment by rbfajardo** [comment]
Same issue as #284

**Comment by DJBenson** [comment]
Please refer to #284. The configuration UI makes a recursive DNS lookup so if external DNS queries are blocked, the lookup will fail. This is intentional to ensure external DNS resolution works for the TXT record.

**Comment by PetieM** [comment]
I realize this was closed a while back but I'm only just now seeing that last comment. For reference, I don't think this is an issue of blocked DNS queries - I think the problem is that the query is failing when the returned key is too long. On a 2048-bit key, from what I remember (I don't have any left to test with now), it worked but 4096-bit keys seem to be problematic.
