### ISSUE TITLE
Exchange 2016 CU10

### ISSUE THREAD

**Issue by nsumner36** [Pro/dkim-exchange#230]
It seems support was added for Exchange 2016 CU10 yet the download doesn't list it and the install file immediately rejects it as an unsupported Exchange version.

How can I install on Exchange 2016 CU10?

**Comment by colinwilson** [comment]
Don't think the GUI package has been released yet.

**Comment by jimbobmcgee** [comment]
Probably a silly question but, why exactly does every new release of Exchange require a new release of this project?  I though Dynamic Link Libraries and Windows Side-By-Side was supposed to take care of this stuff...?

**Comment by boscorelly** [comment]
Because of requirements, name changing, build version changing...

**Comment by Perduarbo** [comment]
Hi, so any news on when the installer will support cu10?

**Comment by jimbobmcgee** [comment]
@boscorelly - how does that really affect the code of dkim-exchange, though?  

I understand that changes occur between between major Exchange versions, but do method, interface and class names really change that frequently between CUs for the *same* major version, to the extent that we couldn't late-bind or otherwise dynamically load the appropriate DLL with `Assembly.LoadFrom(...)` or something?

Maybe it's different in the Exchange team, but I usually find that MS has at least a *reasonable* track-record maintaining backward-compatibility within its libraries.

**Comment by boscorelly** [comment]
Installer is checking some vars such as major and minor version. Have a look at the pushes, you will see :)

**Comment by bkt1916** [comment]
So, can we install it currently? And how?

**Comment by rbfajardo** [comment]
Recommend creating a copy of this code and adding support for CU10 manually then compiling yourself. I added support for CU10 but we have to wait for the author to create a new release which has not been done yet. If you don't want to wait, then your best option is to create a pull request and compile yourself.

Pull Request: https://github.com/Pro/dkim-exchange/pull/229

**Comment by luxzg** [comment]
If the code of dlls don't change, can we safely reuse CU10 to CU11? We did test install yesterday, literally copied dlls to new folder with CU11 name, and added a line to install.ps1. It installed and works correctly so far. If that's the only change, we can do that easily, we don't even need to change the .sln or compile new version of the whole project.

**Comment by h53q9xfd** [comment]
Ninja101's fork is up to date and supports Exchange 2016 CU10.
https://github.com/Ninja101/dkim-exchange
