### ISSUE TITLE
Exchange Server 2016 CU10 

### ISSUE THREAD

**Issue by j0rt3g4** [Pro/dkim-exchange#242]
### Versions
It says that is supported but I got an error message.
Exchange 2016 CU10 (15.1.1531.3) Saying that is unsupported
WS 2016
EX 2016
dkim 3.1.0

**Expected behavior:** To be supported since it's on the supported list

**Actual behavior:** Sending pop up error

**Comment by gilm0079** [comment]
Hi, I'm also trying to install for Exchange 2016 CU10.

I pulled down the repo and compiled it myself.  The application seems to work fine with the latest code, but within the app it must be checking some http location for the latest DKIM Signer to install and only finds version 3.1.0.  I'm guessing a newer build (3.1.1?) needs to be added to the http location it is looking for?  I'm not sure how to get around this at this point.

**Comment by j0rt3g4** [comment]
I don't really remember what I did but I figured it out, what I can do for you is give you my source

**Comment by gilm0079** [comment]
Thanks. This is what I already had.  The problem is within the application is looks for a DKIM signer package at some api.github.com location.  Here is a screenshot illustrating the problem.  The app finds the latest package to be version 3.1.0 which the changelog shows supports Exchange 2016 CU9.  I need it to work for CU10 which the github project says it should.

![dkim-version-issue](https://user-images.githubusercontent.com/3201292/49249273-60154d00-f3e1-11e8-95ab-4330f687c38c.JPG)

**Comment by gilm0079** [comment]
Maybe I'm missing something.  Your provided code looks the same as the github repo.  I'm seeing the same results with your code that it is still trying to pull down the Signer version compiled for Exchange 2016 CU10.  I was more asking if someone with access could update the releases located at:

[https://api.github.com/repos/pro/dkim-exchange/releases](https://api.github.com/repos/pro/dkim-exchange/releases)

Configuration.DkimSigner is not my problem.  That installs fine.  I'm assuming in the UI when it refers to "DKIM Signer" installation it is talking about installing the Exchange.DkimSigner project for the Exchange Transport Role.

If now one has access to this I'll probably just chop the project up to have it reference a local build of Exchange.DkimSigner for the install process instead of trying to fetch it from the online release repo.

**Comment by j0rt3g4** [comment]
OK no I don't have access to it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by j0rt3g4** [comment]
It has to be the same just that mine works on cu10

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gilm0079** [comment]
Weird. Was yours installed before you upgraded to CU10?

When the Configure app tries to install the Exchange app it throws up an error that it is not compatible with my version of exchange.  I'll shoot a message to the repo owner to see if he or I can update the latest release or maybe if a "local" option is added to the Configure app so going forward we can just alternatively point to a local build of the Exchange app.  Thanks.

**Comment by gilm0079** [comment]
@Pro - I don't mind compiling versions or whatever is needed.  I'm trying to run the Configure app for Exchange 2016 CU10.  Your code is updated for this version, but the Configure app reaches out to a api.github.com location for release versions of the Exchange app and that location does not have the CU10 compatible version published there.  

I can update that location if you need help with that.  Or is there a way in the app we can target a local folder for the Exchange app release?  Let me know if I can help otherwise I'll probably just hack apart the code to make it work for me.

Thanks for this time saving app.

**Comment by Latman7** [comment]
> @Pro - I don't mind compiling versions or whatever is needed. I'm trying to run the Configure app for Exchange 2016 CU10. Your code is updated for this version, but the Configure app reaches out to a api.github.com location for release versions of the Exchange app and that location does not have the CU10 compatible version published there.
> 
> I can update that location if you need help with that. Or is there a way in the app we can target a local folder for the Exchange app release? Let me know if I can help otherwise I'll probably just hack apart the code to make it work for me.
> 
> Thanks for this time saving app.

I have the same issue. When I select Reinstall option, it doesn't allow me to select any files. It just goes out to a link and updates it by itself.
Has anyone figured out a way to get this working With Exchange 2016 CU10?
