### ISSUE TITLE
Offline installation documentation is not good enough

### ISSUE THREAD

**Issue by peterM** [Pro/dkim-exchange#262]
In readme file there is: 

![image](https://user-images.githubusercontent.com/2149830/57011047-0e772580-6c00-11e9-9492-8b6f8b0dfad7.png)

But, I do not know from where is possible to download zip package mentioned by point 6.

Is it possible to explain and update documentation? 

Thanks

**Comment by caffari** [comment]
@peterM 

Do the manual install instead.  You can download everything you need from here >> https://github.com/Pro/dkim-exchange/releases/tag/v3.2.0 

Instructions are here >> 
1. Download the .zip and extract it e.g. on the Desktop: Latest Release
2. Open "Exchange Management Shell" from the Startmenu 
3, Check your current execution policy and remember it for the last step Get-ExecutionPolicy –List
4. Execute the following command to allow execution of local scripts (will be reset at last step): Set-ExecutionPolicy Unrestricted 
5. Cd into the folder where the zip has been extracted. 
6. Execute the install script .\install.ps1 
7. Follow the instructions. For the configuration see next section. 
8. Reset the execution policy to the value from step 3. E.g., Set-ExecutionPolicy RemoteSigned or Set-ExecutionPolicy Restricted 
9. Check EventLog for errors or warnings. Hint: you can create a user defined view in EventLog and then select "Per Source" and as the value "Exchange DkimSigner" 

Make sure that the DkimSigner Agent has a "low priority" (high priority number) so that it runs after other agents which might modify the headers. Best to set it to lowest priority (highest number). To get a list of all the Export Agents use the Command Get-TransportAgent To change the priority use Set-TransportAgent -Identity "Exchange DkimSigner" -Priority 3

**Comment by peterM** [comment]
I think mentioned `DkimSigner.zip` == `SourceCode.zip`, but i think this should be mentioned in documentation.

**Comment by DJBenson** [comment]
I am current overhauling the documentation for this project. I have already migrated the documentation from the code repository to the [Wiki](https://github.com/Pro/dkim-exchange/wiki) and will be working on improving the walkthroughs in the coming days.
