### ISSUE TITLE
Please Add support for Exchange 2016 CU15

### ISSUE THREAD

**Issue by d3fc0ndk** [Pro/dkim-exchange#288]
### Versions

- **Windows Server Version**: 2016.1607
- **Exchange Version**: 15.1.1913.5 (CU15)
- **Installed DKIM Exchange Version**: I have tried 2.3.0 and 2.3.1 

### Description

Add support for Exchange 2016 CU15

### Steps to Reproduce

2.3.0:

1. Try to install service in gui
2.  Version not supported window pops up when i try to install.
     Error text: Your Microsoft Exchange version isn't supported by the DKIM agent: 15.1.1913.5

2.3.1 via powershell:

*** Exchange DkimSigner Install Script ***
Detecting Exchange version ...
The exchange version is not yet supported: Version 15.1 (Build 1913.5)
At C:\users\Administrator\src\install.ps1:155 char:2
+     throw "The exchange version is not yet supported: " + $exchserver ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The exchange ve... (Build 1913.5):String) [], RuntimeException
    + FullyQualifiedErrorId : The exchange version is not yet supported: Version 15.1 (Build 1913.5)

**Expected behavior: Add support for Exchange 2016 CU15

**Actual behavior: Add support for Exchange 2016 CU15

**Comment by DJBenson** [comment]
https://github.com/DJBenson/dkim-exchange/releases/tag/v3.2.3

**Comment by Fluffythesheep** [comment]
Hi DJBenson, Thank you, but the link you provided, i downloaded the configuration.dkim, this still seems to reference and download the version 3.2.0

**Comment by DJBenson** [comment]
> Hi DJBenson, Thank you, but the link you provided, i downloaded the configuration.dkim, this still seems to reference and download the version 3.2.0

Where are you getting the version number from, and how are you installing the app? Until my changes get merged into this repository, you'll have to perform an [offline](https://github.com/Pro/dkim-exchange#offline-install) or [manual](https://github.com/Pro/dkim-exchange#manual-install) install using the full source package rather than the installer. The installer will always pull the latest version from this repo which is 3.2.0 until @Pro merges in my changes.

Follow the instructions linked above, but obviously pull the binaries/source from my repo rather than here or you'll be stuck on 3.2.0.

You should end up with the config looking like this:
![Screenshot_1](https://user-images.githubusercontent.com/1013909/71847725-91bd1500-30c5-11ea-882e-9c01b028ecb5.png)

I am trying to work out how to update the config tool to pull from my repo then I can completely detach from this one because it does appear abandoned and it would be easier for me to maintain it without the calls back to the original repo if I'm honest.

**Comment by stryqx** [comment]
> I am trying to work out how to update the config tool to pull from my repo then I can completely detach from this one because it does appear abandoned and it would be easier for me to maintain it without the calls back to the original repo if I'm honest.

Modifying Line 17 in Src/Configuration.DkimSigner/GitHub/ApiWrapper.cs
should do it.

-- 
Regards,
Chris Knight

**Comment by DJBenson** [comment]
> I am trying to work out how to update the config tool to pull from my repo then I can completely detach from this one because it does appear abandoned and it would be easier for me to maintain it without the calls back to the original repo if I'm honest.
> Modifying Line 17 in Src/Configuration.DkimSigner/GitHub/ApiWrapper.cs should do it.
> […](#)
> -- Regards, Chris Knight

Yeah I'd hoped it was that easy but I tried that previously and it just causes the UI to crash on launch with the following (sorry for the crappy formatting);

I'm not sure how the app is authenticating with GitHub (if at all) but from what I can see GitHub requires some OAuth or user key to use their API which I think the config UI is doing, so it's probably crashing because it's trying to reach a repository (mine) with the OAuth token/key for the original repo. I trawled through the code and can't see where this is configured.

----------------------------------------

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Configuration.DkimSigner.MainWindow.<CheckDkimSignerAvailable>d__21.MoveNext() in C:\Users\jonathan.thomson\Documents\GitHub\dkim-exchange\Src\Configuration.DkimSigner\MainWindow.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Configuration.DkimSigner
    Assembly Version: 3.2.3.0
    Win32 Version: 3.2.3
    CodeBase: file:///C:/Release/Configuration.DkimSigner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.771
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
Microsoft.PowerShell.Commands.Diagnostics
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Diagnostics/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Diagnostics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
Microsoft.PowerShell.ConsoleHost
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.ConsoleHost/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.ConsoleHost.dll
----------------------------------------
Microsoft.PowerShell.Commands.Utility
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Utility/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Utility.dll
----------------------------------------
Microsoft.PowerShell.Commands.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Commands.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Commands.Management.dll
----------------------------------------
Microsoft.Management.Infrastructure
    Assembly Version: 1.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Management.Infrastructure/v4.0_1.0.0.0__31bf3856ad364e35/Microsoft.Management.Infrastructure.dll
----------------------------------------
Microsoft.PowerShell.Security
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.PowerShell.Security/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.PowerShell.Security.dll
----------------------------------------
Microsoft.WSMan.Management
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.17763.348
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.WSMan.Management/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.WSMan.Management.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Microsoft.Exchange.PowerShell.Configuration
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0529.005
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.PowerShell.Configuration.dll
----------------------------------------
Microsoft.Exchange.Data.Directory
    Assembly Version: 15.0.0.0
    Win32 Version: 15.02.0529.005
    CodeBase: file:///C:/Program%20Files/Microsoft/Exchange%20Server/V15/bin/Microsoft.Exchange.Data.Directory.DLL
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by DJBenson** [comment]
Mmm perhaps not, I can browse to the URL the app is calling without authenticating:

https://api.github.com/repos/djbenson/dkim-exchange/releases

Something else is causing the app to crash on launch when it's calling out to that URL in ApiWrapper.cs when it's changed from the original repo...

**Comment by DJBenson** [comment]
Worked it out - it's because the releases from this repo are not cloned into my repo for some reason, and the app expects one "Release" version and an optional "Pre-release" version (the changelog in the UI is created dynamically from the available releases).

As I merged v3.2.2 to my master branch anyway I removed the "Pre-release" tag from it and the app launches.

Not ideal currently as only my releases are showing in the UI but I'll see what I can do about that.

**Comment by DJBenson** [comment]
Mmm not sure how to handle this (I'm not GIT expert so any help on this would be appreciated).

When I forked the repo, all the code and tags were forked but no binary releases were included. I've since added two releases of my own (v3.2.2 and v3.2.3) which both show up in the GitHub UI and also the Configuration.DkimSigner app but none of the old (v3.2.0 and earlier) releases were forked. I can manually create a release for each tag but there are many drawbacks;

1. It would take too much of my time
2. I need to manually download the zip file for the release and upload it to my newly created release
3. The changelog in Configuration.DkimSigner is ordered by release create date seemigly so the releases are out of order

Any suggestions greatly appreciated. For now though I will check in a fix under v3.2.3.1 which updates the URL for the repository so I can begin to control releases properly. In the meantime, if @Pro checks in on this thread, I'd be happy to take over maintenance of the project.

**Comment by DJBenson** [comment]
I've just released [v3.2.3.1](https://github.com/DJBenson/dkim-exchange/releases/tag/v3.2.3.1) which includes all my recent changes (EX2016 CU15, EX2019 CU3, EX2019CU4) and some fixes to ensure the configuration UI calls my repository rather than this one. If you want continued builds, please consider updating to this version.

Once my version is installed, you will be able to use the integrated update functionality to update to pre-release and release versions from v3.2.2 onwards.

**NOTE**

There's no point in providing releases < v3.2.2 as each release is backwards compatible anyway so you will only see versions v3.2.2 onwards with this build. I will aim to keep one release channel and one pre-release channel available as and when Exchange CU's are released.

New CU will be pre-release (e.g. Exchange 2019 CU4)
Previous CU will be release (e.g. Exchange 2019 CU3 after CU4 is released).

**Comment by Pro** [comment]
@DJBenson thank you for all your work!

I added you as a collaborator to this project. This should give you the rights to merge pull requests and also create new releases. IMHO it would be best if we avoid splitting forks.
You can then also remove the "Maintainer wanted" note in the README if you are interested in keeping this repo up-to-date?!

**Comment by DJBenson** [comment]
> @DJBenson thank you for all your work!
> 
> I added you as a collaborator to this project. This should give you the rights to merge pull requests and also create new releases. IMHO it would be best if we avoid splitting forks.
> You can then also remove the "Maintainer wanted" note in the README if you are interested in keeping this repo up-to-date?!

Thanks @Pro 

I've just tidied up this thread a bit - I agree keeping everything here makes more sense and now you've given me collaborator access I can help to keep this repo up to date.

**Comment by DJBenson** [comment]
The latest code and binary releases have now been added to this repository so no need to go searching elsewhere.

I have tested the automated install/upgrade process and can confirm it works so anybody on an older version should see the new version (currently [v3.2.3](https://github.com/Pro/dkim-exchange/releases/tag/v3.2.3)) and be able to download and install/upgrade the application directly from the DKIM Signer UI.

**Comment by DJBenson** [comment]
Closing as requested versions/CU's have been added to the latest release.
