### ISSUE TITLE
Cannot use dots in the selector field

### ISSUE THREAD

**Issue by RostKost** [Pro/dkim-exchange#77]
Error message: The selector should only contain characters, numbers and underscores. 
So, I cannot use hostname feb2009.myesp._domainkey.example.com

http://dkimcore.org/specification.html
A selector is a string of no more than 63 lower-case alphanumeric characters (a-z or 0-9) followed by a period “.”, followed by another string of no more than 63 lower-case alphanumeric characters.

--
Rostislav.

**Comment by Pro** [comment]
Oh, yes. That's a bug, namely this check is wrong:
https://github.com/Pro/dkim-exchange/blob/master/Src/Configuration.DkimSigner/MainWindow.cs#L234
The regex should be something like `^[a-z0-9_]{1,63}(?:\.[a-z0-9_]{1,63})?$`

Until this is fixed in the next release, you can just add the selector without a point, then open the config file and edit the selector to contain a point (see https://github.com/Pro/dkim-exchange#manual-configuration)
