### ISSUE TITLE
Exchange 2003 support

### ISSUE THREAD

**Issue by MasterII** [Pro/dkim-exchange#79]
Hello,
I appreciate your DKIM agent for Exchange servers.

I have also many Exchange 2003 server running, boosting with some additional "sinks". Antivirus, greylist, spamassasin. But I could not find nothing for DKIM signing. Email architects cost 300$ for that, if consider, that total cost of SBS2003 solutions was about 250$ is quite out of mind. Exchange2003 is still very good email server, doing its work well. But we really want to fight with spam and establish signed email senders from our domains via DKIM.

Do you really think, you never make any vesion for Exchange2003? We can consider appropriate donation for this sink.

Sincerelly,
Jiri Vlk

**Comment by Pro** [comment]
Writing an issue is fine for that :)
At least it is not planned to implement Support for Exchange 2003.
If you are also willing to test the implementation afterwards (as a beta tester), I can give it a try, but no promises?

I'll have to install Exchange 2003 on a virtual machine for that. Can you tell me exactly which Windows Version and which Exchange 2003 version you are using? (Installed Service Packs and so on...)

Currently I don't have much spare time, so it will take probably a few weeks until a test version is ready.

Donations are always welcome. I added a donation pledge for this purpose to the main page.

**Comment by MasterII** [comment]
Hello,

thank you for reply.

 

Yes, I can help with testing. I am not coder programmer at all, but windows systems administrator is my job.

 

I am running latest major version of Exchange 2003 Standard / Enterprise ServicePack 2. Exchange 2003 standard SP2 is included in Small Business Server 2003. (no windows update if it was not required by another system component)

Whole environments are combination of Windows Server 2003 SP2 / Windows Server 2003 R2 + Exchange 2003 Standard SP2 / Exchange 2003 Enterprise SP2.

 

I tried https://www.emailarchitect.net/domainkeys/

It works, but is also too expensive.

 

Sincerely,

Jiri Vlk

**Comment by AlexLaroche** [comment]
Hi  Masterli,

Can you upload this four files? The file are locate under "C:\Program Files\Microsoft\Exchange Server\Public" by default.

Microsoft.Exchange.Data.Common.dll
Microsoft.Exchange.Data.Common.xml
Microsoft.Exchange.Data.Transport.dll
Microsoft.Exchange.Data.Transport.xml

Can you also post the result of this two commands (powershell)?

$hostname = hostname
$exchserver = Get-ExchangeServer -Identity $hostname

Regards,

**Comment by MasterII** [comment]
Hello,

there are no such files on Exchange 2003 SP2 installed on Windows 2003 server SP2 /R2. Also PowerShell is not common part of Windows 2003 server. Only PS 1.0 can be installed on Windows 2003 server, I am not using it in production environments.

If you need „local“ working Exchange 2003 machine, I can provide you one as a virtual machine. Just clear Windows 2003 server SP2 + Exchange 2003 standard SP2 for development and testing.

 

Some similar files

Microsoft.Exchange.Transport.EventInterop.dll

Microsoft.Exchange.Transport.EventWrappers.dll

I have found in instalation dir of custom sinks GreyList and ClamWin. I can send you this addons for looking how another sink is implemented. Unfortunately I do not have source code.

 

I do not want to cause any licence violation, so I rather send it to your email directly, not via github.

 

JV

**Comment by AlexLaroche** [comment]
Hi Masterli,

I have you ever considerate migrate your anti-spam server? Microsoft stopped supporting Exchange 2003 last year and it will stop supporting Windows 2003 this year. Microsoft support the two last version of Exchange for their release you will be face of a problem one day. (Exchange 2013 > 2007, Exchange 2010 > 2003, Next release > 2010)

You can done really good and cheap anti-spam solution by yourself if you are comfortable with Linux. Some pre-build distributions exist. You can also buy good anti-spam solution. (Example : Barracuda | Spam firewall)

It will take a lot of hard work to be compatible for Exchange 2003 for the GUI because most of the operation are done in Powershell behind but I think it's possible to use the current code of the agent to run on Exchange 2003 without a lot of efforts. All the process for install and uninstall will have to be done manually.

Basically, we need to create a another project in the solution. We will reuse the code of the current agent but we will have to rewrite two class "DkimSigningRoutingAgent.cs" and "DkimSigningRoutingAgentFactory.cs".

We will need to have a copy of this two DLL:
Microsoft.Exchange.Transport.EventInterop.dll
Microsoft.Exchange.Transport.EventWrappers.dll

I can give it a try, but no promises.

As Stephan (Pro) answered, it was not planned to implement support for Exchange 2003 for the reasons I mentioned. (Exchange 2003 is no more supported by Microsoft.)

Currently I don't have much spare time like Stephan (Pro), so it will take probably a few weeks before I can try the implementation if you really want to try.

Alex

**Comment by Pro** [comment]
In my opinion supporting such an old version which requires a lot of code changes and which complicates the code additionally wouldn't be a good solution. I'm not really a fan of that.

@AlexLaroche if we really implement Exchange 2003 support, we should create a new branch for it to keep our master branch clear of the changes and merge any changes from the master to this special Exchange 2003 branch.

**Comment by MasterII** [comment]
I am not forcing you into Exchange 2003 support. It should be great, but not necessary.

Just look at it without any version/age scale. SMTP itself is a standard, such a standard Exchange 2003 can handle perfectly. Any Microsoft "life circle/support" is just a profit level. Unless anything will change in SMTP communication, there is no old email server until it will be able communicate with others. Probably we will apply for GoogleApps in far future. No investment plans for now.

Where I can send requested files?
Microsoft.Exchange.Transport.EventInterop.dll
Microsoft.Exchange.Transport.EventWrappers.dll

I can attach only images to my post.

**Comment by AlexLaroche** [comment]
I'm not sure if I will try the implementation. For the moment, I don't have the time to don't it.
Can you upload the file in a ZIP file on WeTransfer? https://www.wetransfer.com/
If I decide to try the implement I would have the require files.

SMTP is standard but Exchange 2003 isn't more supported by Microsoft. If the server have a vulnerability, it will not be patch. It can be a risk for the security for your IT environment. In this example, a vulnerability permit for a exploit to do remote code execution but it's your decision. 
https://technet.microsoft.com/library/security/ms04-035

**Comment by AlexLaroche** [comment]
Exchange 2003 will not be supported.
